// netlify/functions/lib/playScrape.mjs
//
// Reads the latest published result for each game from play.nla.gd.
//
// WHY TEXT, NOT CSS SELECTORS
// The page is server-rendered but its markup is generated by the Abrazo web
// sales platform and can change without notice. Matching on tag structure
// would break silently on any redesign. This works on the visible TEXT and the
// game logo filenames instead, which are far more stable, and it reports what
// it could not find rather than returning a half-empty result.
//
// WHAT THIS CAN AND CANNOT SUPPLY
//   supplies : winning numbers, Multi-X, the draw's date and time, jackpots
//   does NOT : draw numbers, payouts, prize tiers, or any history
// The draw number is derived from what the app already holds and must be
// confirmed by an operator. Nothing here is ever published automatically.

const PAGE = 'https://play.nla.gd/websales/';

// The logo filename is how each block is identified.
const GAME_BY_LOGO = {
  'playway-logo': 'play_way',
  'cash4-logo':   'cash4',
  'daily3-logo':  'pick3',
  'lotto-logo':   'lotto',
  'super6-logo':  'super6',
  'cashpop-logo': 'cash_pop',
};

// Draw time -> our period code.
const DAILY_BY_TIME = {
  '09:45': 'mid_morning', '12:45': 'midday',
  '16:45': 'mid_afternoon', '19:45': 'evening',
};
const POP_BY_TIME = {
  '08:45': 'kick_off', '11:45': 'lunch', '14:45': 'mid_rush',
  '17:45': 'after_work', '20:45': 'prime_time',
};

const MONTHS = { jan:1, feb:2, mar:3, apr:4, may:5, jun:6,
                 jul:7, aug:8, sep:9, oct:10, nov:11, dec:12 };

// What each game's result can actually be. The page has no delimiter after the
// last block, so a greedy match runs on into the footer — "473 440 7050" is the
// contact number and "2026" the copyright year. Taking only the expected count,
// and rejecting anything out of range, makes the parse immune to whatever
// follows on the page.
const SHAPE = {
  play_way: { count: 1, min: 1,  max: 36 },
  pick3:    { count: 3, min: 0,  max: 9  },
  cash4:    { count: 4, min: 0,  max: 9  },
  cash_pop: { count: 1, min: 1,  max: 15 },
  lotto:    { count: 5, min: 1,  max: 34 },
  super6:   { count: 6, min: 1,  max: 28 },
};

/** '07:45 PM' -> '19:45' */
export function to24h(time) {
  const m = /^(\d{1,2}):(\d{2})\s*(AM|PM)$/i.exec(String(time).trim());
  if (!m) return null;
  let h = Number(m[1]) % 12;
  if (/PM/i.test(m[3])) h += 12;
  return `${String(h).padStart(2, '0')}:${m[2]}`;
}

/**
 * 'Sat 12 Sep' -> '2026-09-12'.
 * The page omits the year, so it is inferred: a month more than six ahead of
 * today belongs to last year. That handles the turn of the year without
 * needing the page to tell us.
 */
export function toIsoDate(text, today = new Date()) {
  const m = /(\d{1,2})\s+([A-Za-z]{3})/.exec(String(text));
  if (!m) return null;
  const day = Number(m[1]);
  const mon = MONTHS[m[2].toLowerCase()];
  if (!mon) return null;

  let year = today.getUTCFullYear();
  const monthsAhead = mon - (today.getUTCMonth() + 1);
  if (monthsAhead > 6) year -= 1;
  if (monthsAhead < -6) year += 1;

  return `${year}-${String(mon).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
}

/** Strip markup and collapse whitespace, keeping logo names as markers. */
function toText(html) {
  return String(html)
    .replace(/<img[^>]*src="[^"]*\/([a-z0-9]+-logo)[^"]*"[^>]*>/gi, ' ⟦$1⟧ ')
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Pull each game's latest result out of the page text.
 * Returns { results: [...], problems: [...] }.
 */
export function parsePlayPage(html, today = new Date()) {
  const text = toText(html);
  const results = [];
  const problems = [];

  // Split on the logo markers so each chunk belongs to one game.
  const chunks = text.split('⟦').slice(1);
  const seen = new Set();

  for (const chunk of chunks) {
    const close = chunk.indexOf('⟧');
    if (close < 0) continue;
    const logo = chunk.slice(0, close);
    const game = GAME_BY_LOGO[logo];
    if (!game || seen.has(game)) continue;

    const body = chunk.slice(close + 1);

    // "Latest Results Sat 12 Sep 07:45 PM 33 MX: FP"
    const m = /Latest Results\s+([A-Za-z]{3}\s+\d{1,2}\s+[A-Za-z]{3})\s+(\d{1,2}:\d{2}\s*(?:AM|PM))\s+([^⟦]*?)(?=Next Draw|Latest Results|Play\b|Buy Tickets|Call us|Privacy|©|$)/i
      .exec(body);
    if (!m) continue;                       // the block may be a nav duplicate

    seen.add(game);

    const isoDate = toIsoDate(m[1], today);
    const time24  = to24h(m[2]);
    const tail    = m[3].trim();

    if (!isoDate || !time24) {
      problems.push(`${game}: could not read the draw date or time.`);
      continue;
    }

    // "33 MX: FP"  |  "9 6 1 1 MX: FP"  |  "06 20 29 32 33 B"  |  "11"
    const mxMatch = /MX:\s*([A-Za-z0-9]+)/i.exec(tail);
    const multiplier = mxMatch ? mxMatch[1].toUpperCase() : null;

    const withoutMx = tail.replace(/MX:\s*[A-Za-z0-9]+/i, ' ').trim();
    const letterMatch = /\b([A-O])\b\s*$/.exec(withoutMx);
    const letter = (game === 'lotto' || game === 'super6') && letterMatch
      ? letterMatch[1] : null;

    const numberPart = letter ? withoutMx.replace(/\b[A-O]\b\s*$/, '') : withoutMx;
    const shape = SHAPE[game];
    const found = (numberPart.match(/\d+/g) || []).map(Number);

    // Keep only as many as this game has, then check they are in range. Both
    // guards matter: the count stops footer text being read as results, and the
    // range catches a mis-parse that happens to have the right length.
    const numbers = found.slice(0, shape.count);

    if (numbers.length < shape.count) {
      problems.push(
        `${game}: expected ${shape.count} number${shape.count === 1 ? '' : 's'} `
        + `but read ${numbers.length}.`);
      continue;
    }

    const outOfRange = numbers.filter((n) => n < shape.min || n > shape.max);
    if (outOfRange.length) {
      problems.push(
        `${game}: ${outOfRange.join(', ')} outside the valid range `
        + `${shape.min}-${shape.max}. The page may have changed.`);
      continue;
    }

    const period = game === 'cash_pop' ? POP_BY_TIME[time24]
      : (game === 'lotto' || game === 'super6') ? null
      : DAILY_BY_TIME[time24];

    if (period === undefined) {
      problems.push(`${game}: ${time24} is not a scheduled draw time.`);
      continue;
    }

    // Jackpot appears before "Play" for the two jackpot games.
    let jackpot = null;
    if (game === 'lotto' || game === 'super6') {
      const j = /([\d,]{4,})\s*(?:\[)?Play/i.exec(body);
      if (j) jackpot = Number(j[1].replace(/,/g, ''));
    }

    results.push({
      game, drawDate: isoDate, time: time24, period,
      numbers, multiplier, letter, jackpot,
    });
  }

  for (const g of Object.values(GAME_BY_LOGO)) {
    if (!seen.has(g)) problems.push(`${g}: no result block found on the page.`);
  }

  return { results, problems, fetchedAt: new Date().toISOString() };
}

/** Fetch and parse. Network and parse failures are reported, never thrown. */
export async function fetchLatestResults() {
  let html;
  try {
    const res = await fetch(PAGE, {
      headers: { 'User-Agent': 'NLA-ResultsDesk/1.0 (+https://nla.gd)' },
    });
    if (!res.ok) {
      return { results: [], problems: [`play.nla.gd returned ${res.status}.`] };
    }
    html = await res.text();
  } catch (e) {
    return { results: [], problems: [`Could not reach play.nla.gd: ${e.message}`] };
  }
  return parsePlayPage(html);
}
